services:
  - name: todoless-server
    type: web
    runtime: node
    plan: free
    rootDir: server
    buildCommand: pnpm install && pnpm build && pnpm seed
    startCommand: pnpm start
    repo: https://github.com/gkfat/todoless.git
    branch: master
    healthCheckPath: /api/v1/health
    envVars:
      - fromGroup: todoless-env-group

  - name: todoless-client
    type: web
    plan: free
    rootDir: client
    runtime: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/gkfat/todoless.git
    branch: master
    healthCheckPath: /

  - name: todoless-redis
    type: redis
    plan: free
    ipAllowList: [{ source: '0.0.0.0/0' }]
